server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      routes:
        - id: person-server-users
          uri: lb://person-server
          predicates:
            - Path=/users/**
            
        - id: person-server-auth
          uri: lb://person-server
          predicates:
            - Path=/auth/**

        - id: sport-server
          uri: lb://sport-server
          predicates:
            - Path=/sport/**
