server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/PacoMatias89/microservicio_usuario_deportes
          search-paths: config-data
  application:
    name: config-server  